/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.estruturadedados.telas;

import com.estruturadedados.dao.produto.ProdutoDAO;
import com.estruturadedados.dto.produto.Fila;
import com.estruturadedados.dto.produto.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Vieira
 */
public class Cadastro extends javax.swing.JFrame {

    private Fila filaProdutos = new Fila();

    private String nomeP;
    private long cod;
    private String marcaP;
    private int categoria;

    private boolean verifica1 = false;
    private boolean verifica2 = false;
    private boolean verifica3 = false;
    private boolean verifica4 = false;

    public Cadastro() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        caixaDeEscolha = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        verificaNome = new javax.swing.JButton();
        verificaCod = new javax.swing.JButton();
        verificaMarca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Produtos");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("NOME DO PRODUTO: ");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("MARCA/DISTRIBUIDORA: ");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("COD. DE BARRAS: ");

        caixaDeEscolha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        caixaDeEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIMPEZA", "ALIMENTO", "BEBIDA", "DESPACHE" }));
        caixaDeEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeEscolhaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("CATEGORIA:");

        cadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        verificaNome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        verificaNome.setText("OK");
        verificaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaNomeActionPerformed(evt);
            }
        });

        verificaCod.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        verificaCod.setText("OK");
        verificaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaCodActionPerformed(evt);
            }
        });

        verificaMarca.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        verificaMarca.setText("OK");
        verificaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(caixaDeEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marca, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(codigo))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(verificaMarca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verificaNome)
                                    .addComponent(verificaCod))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(cadastrar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificaNome))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificaCod))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificaMarca))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaDeEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltar)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaDeEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeEscolhaActionPerformed
        // TODO add your handling code here:

        if (verifica1 && verifica2 && verifica3) {
            String str = (String) caixaDeEscolha.getSelectedItem();

            if (str.equals("LIMPEZA")) {
                categoria = 1;
                verifica4 = true;
            } else if (str.equals("ALIMENTO")) {
                categoria = 2;
                verifica4 = true;
            } else if (str.equals("BEBIDA")) {
                categoria = 3;
                verifica4 = true;
            } else {
                categoria = 0;
                verifica4 = true;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos anteriores!");
        }


    }//GEN-LAST:event_caixaDeEscolhaActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:

        if (verifica1 && verifica2 && verifica3 && verifica4) {

            Produto p = new Produto();

            p.setNome(nomeP);
            p.setCodigoDeBarras(cod);
            p.setMarca(marcaP);
            p.setCategoria(categoria);

            filaProdutos.adiciona(p);

            int resposta;

            while (true) {
                try {
                    resposta = Integer.parseInt(JOptionPane.showInputDialog("Deseja continuar Cadastrando? [1] Sim [0] Não"));
                    verifica1 = false;
                    verifica2 = false;
                    verifica3 = false;
                    verifica4 = false;
                    nome.setText(null);
                    codigo.setText(null);
                    marca.setText(null);
                    if (resposta > 1 || resposta < 0) {
                        JOptionPane.showMessageDialog(null, "Opção Inválida! - Tente novamente");
                    }else{
                        if (resposta == 1) {
                            break;
                        }else{
                            ProdutoDAO banco = new ProdutoDAO();
                            banco.inserirProdutos(filaProdutos);
                            dispose();
                            Menu m  = new Menu();
                            m.setVisible(true);
                            break;
                        }
                    }
                    
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Formato de número inválido!");
                }
                
            }

        } else {
            JOptionPane.showMessageDialog(null, "Os campos anteriores não foram preenchidos!");
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void verificaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaNomeActionPerformed
        // TODO add your handling code here:
        if (nome.getText().equals("") || nome.getText() == null) {
            JOptionPane.showMessageDialog(null, "Escreva o nome do produto!");
            nome.setText("");
        } else {
            nomeP = nome.getText();
            verifica1 = true;
        }


    }//GEN-LAST:event_verificaNomeActionPerformed

    private void verificaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaCodActionPerformed
        // TODO add your handling code here:
        if (verifica1) {

            try {
                cod = Long.parseLong(codigo.getText());
                verifica2 = true;

            } catch (NumberFormatException e) {
                if (codigo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o código de barras!");
                    return;
                }
                JOptionPane.showMessageDialog(null, "Formato de número inválido!");
                codigo.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Insira o nome do produto primeiro!");
            codigo.setText("");
        }
    }//GEN-LAST:event_verificaCodActionPerformed

    private void verificaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaMarcaActionPerformed
        // TODO add your handling code here:

        if (verifica1 && verifica2) {
            if (marca.getText().equals("") || marca.getText() == null) {
                JOptionPane.showMessageDialog(null, "Escreva o nome da marca!");
                marca.setText("");
            } else {
                marcaP = marca.getText();
                verifica3 = true;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos anteriores!");
        }
    }//GEN-LAST:event_verificaMarcaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JComboBox<String> caixaDeEscolha;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nome;
    private javax.swing.JButton verificaCod;
    private javax.swing.JButton verificaMarca;
    private javax.swing.JButton verificaNome;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
