/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.estruturadedados.telas;

import com.estruturadedados.dao.produto.ProdutoDAO;
import com.estruturadedados.dto.produto.Fila;

/**
 *
 * @author Rafael Vieira
 */
public class Consulta extends javax.swing.JFrame {

    public Consulta() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        painel = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        caixaDeEscolha = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        mostrar.setEditable(false);
        mostrar.setColumns(20);
        mostrar.setRows(5);
        painel.setViewportView(mostrar);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Produtos");

        caixaDeEscolha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        caixaDeEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTEIRA P. DE LIMPEZA", "ESTEIRA P. DE ALIMENTO", "ESTEIRA P. DE BEBIBAS", "DESPACHE" }));
        caixaDeEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeEscolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caixaDeEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(caixaDeEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:

        dispose();

        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void caixaDeEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeEscolhaActionPerformed
        // TODO add your handling code here:
        String str = (String) caixaDeEscolha.getSelectedItem();

        if (str.equals("ESTEIRA P. DE LIMPEZA")) {
            ProdutoDAO x = new ProdutoDAO();

            Fila limpeza = x.consultarEsteiraLimpeza();

            if (limpeza.filaVazia()) {
                String texto = "--- Nenhum produto foi cadastrado ---";
                x.resetarEsteiraLimpeza();
                mostrar.setText(texto);

            } else {
                String texto = "";
                for (int i = 0; i < limpeza.tamanhoReal(); i++) {
                    texto += "ID: " + limpeza.percorrerFila(limpeza, i).getId() + "\t";
                    texto += "Nome:" + limpeza.percorrerFila(limpeza, i).getNome() + "\t";
                    texto += "Cod. de Barras:" + limpeza.percorrerFila(limpeza, i).getCodigoDeBarras() + "\t";
                    texto += "Marca:" + limpeza.percorrerFila(limpeza, i).getMarca() + "\t";
                    texto += "Categoria:" + limpeza.percorrerFila(limpeza, i).getCategoria() + "\t";
                    texto += "\n";
                    mostrar.setText(texto);
                }

            }

        } else if (str.equals("ESTEIRA P. DE ALIMENTO")) {
            ProdutoDAO x = new ProdutoDAO();

            Fila alimento = x.consultarEsteiraAlimento();

            if (alimento.filaVazia()) {
                String texto = "--- Nenhum produto foi cadastrado ---";
                x.resetarEsteiraAlimento();
                mostrar.setText(texto);

            } else {
                String texto = "";

                for (int i = 0; i < alimento.tamanhoReal(); i++) {
                    texto += "ID: " + alimento.percorrerFila(alimento, i).getId() + "\t";
                    texto += "Nome:" + alimento.percorrerFila(alimento, i).getNome() + "\t";
                    texto += "Cod. de Barras:" + alimento.percorrerFila(alimento, i).getCodigoDeBarras() + "\t";
                    texto += "Marca:" + alimento.percorrerFila(alimento, i).getMarca() + "\t";
                    texto += "Categoria:" + alimento.percorrerFila(alimento, i).getCategoria() + "\t";
                    texto += "\n";
                }

                mostrar.setText(texto);
            }

        } else if (str.equals("ESTEIRA P. DE BEBIBAS")) {
            ProdutoDAO x = new ProdutoDAO();

            Fila bebida = x.consultarEsteiraBebidas();

            if (bebida.filaVazia()) {
                String texto = "--- Nenhum produto foi cadastrado ---";
                x.resetarEsteiraBebidas();
                mostrar.setText(texto);
            } else {
                String texto = "";

                for (int i = 0; i < bebida.tamanhoReal(); i++) {
                    texto += "ID: " + bebida.percorrerFila(bebida, i).getId() + "\t";
                    texto += "Nome:" + bebida.percorrerFila(bebida, i).getNome() + "\t";
                    texto += "Cod. de Barras:" + bebida.percorrerFila(bebida, i).getCodigoDeBarras() + "\t";
                    texto += "Marca:" + bebida.percorrerFila(bebida, i).getMarca() + "\t";
                    texto += "Categoria:" + bebida.percorrerFila(bebida, i).getCategoria() + "\t";
                    texto += "\n";
                }

                mostrar.setText(texto);
            }

        } else {

            ProdutoDAO x = new ProdutoDAO();

            Fila despache = x.consultarEsteiraDespache();

            if (despache.filaVazia()) {
                String texto = "--- Nenhum produto foi cadastrado ---";
                x.resetarDespache();
                mostrar.setText(texto);

            } else {
                String texto = "";

                for (int i = 0; i < despache.tamanhoReal(); i++) {
                    texto += "ID: " + despache.percorrerFila(despache, i).getId() + "\t";
                    texto += "Nome:" + despache.percorrerFila(despache, i).getNome() + "\t";
                    texto += "Cod. de Barras:" + despache.percorrerFila(despache, i).getCodigoDeBarras() + "\t";
                    texto += "Marca:" + despache.percorrerFila(despache, i).getMarca() + "\t";
                    texto += "\n";
                }

                mostrar.setText(texto);
            }

        }
    }//GEN-LAST:event_caixaDeEscolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caixaDeEscolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea mostrar;
    private javax.swing.JScrollPane painel;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
